# Generated by Django 4.2.1 on 2023-08-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PullRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(max_length=20)),
                ("title", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=50)),
                ("link", models.CharField(max_length=200)),
                ("updated_at", models.CharField(max_length=100)),
                ("review_requested", models.TextField()),
            ],
        ),
    ]
