# Generated by Django 4.2.1 on 2023-08-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_pullrequest_link_alter_pullrequest_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="pullrequest",
            name="claimed",
            field=models.CharField(blank=True, default="", max_length=200),
        ),
    ]
